### ISSUE TITLE
Update introduction in viz 2: NL-BE

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#122]
Currently:

> This visualization shows [one week of intense bird migration](https://github.com/enram/case-study) over the Netherlands and Belgium.
> 
> The data are recorded in April 2013 by 5 weather radars (indicated as gray circles). We aggregate the data over time and altitude, and interpolate those over a larger area. We then release particles (indicated in blue) in the interpolated grid, which represent the speed and direction of the bird migration at that moment. The grid is updated every second with data from the next 20 minute interval, which updates the speed and direction of the particles.
> 
> The visualization was developed by [LifeWatch INBO](https://twitter.com/LifeWatchINBO) for [ENRAM](http://enram.eu/), the European Network for the Radar Surveillance of Animal Movement. The long-term goal of ENRAM is to retrieve and visualize this kind of data at a European scale. Documentation and source code are available on [GitHub](https://github.com/enram/bird-migration-flow-visualization).

**Comment by peterdesmet** [comment]
@jshamoun @hvangasteren can you review and update the introduction?

1. The first paragraph summarizes what this visualization is about
2. The second paragraph explains how it works
3. The third paragraph lists the partners, long term goal and link to GitHub

* [ ] Suggestions for the text?
* [ ] Probably better to add link to GitHub in second paragraph?
* [ ] Which partners should we add?
* [ ] Should this text come before, after or next to the visualization?
* [ ] Should we list the improvements over the older version?

We'll have to do the same exercise for the US case study.

**Comment by jshamoun** [comment]
This visualization shows one week of intense bird migration over the Netherlands and Belgium.

The data were recorded in April 2013 by 5 weather radars (indicated as gray circles). We aggregate the data over time and altitude, and interpolate those over a larger area. We then release particles (indicated in blue) in the interpolated grid, which represent the speed and direction of the bird migration at that moment. The grid is updated every second with data from the next 20 minute interval, which updates the speed and direction of the particles. This case study is also briefly described in the following paper [link move ecol paper ]. >> although we should probably wait and add link to current paper, but in any case I would like a link to our publications

(below not sure how to write this and keep concise, but I would like to mention the people involved or at least the groups and the expertise, also along emphasis in paper - moving towards interdisciplinary collaboration, should really mention that this was part of an STSM funded by COST).  
The visualization was developed by LifeWatch INBO for ENRAM, the European Network for the Radar Surveillance of Animal Movement. The long-term goal of ENRAM is to retrieve and visualize radar measurements of animal movement at a European scale (link to move ecol paper could go here). The visualization is part of an interdisciplinary collaboration that was hosted by Computational Geo-Ecology at the University of Amsterdam and included ecologists (UvA), meteorologists (KNMI) and scientific programmers (or some general label you prefer LifeWatch INBO).

Documentation and source code are available on GitHub.

**Comment by jshamoun** [comment]
Where to put the visualization depends a bit on visual preference I think. It would be nice to know right away what you are looking at, but perhaps you don't want to be bothered with all the text.  It also takes up space of course. 

I am not sure if you need to mention improvements of the old version, that depends on how much emphasis you want to give on the process.  You could have a brief blurb about the main points with a text that can be expanded (with a read more link or something similar).

Perhaps in the text you should also mention that the length of the vectors represents relative speed, the longer the vector the higher the speed.

Hope this is helpful.
