### ISSUE TITLE
Gaps in the data?

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#68]
The animation seems to stop from time to time, e.g. at `April 10 2013, 08:40` in the highest altitude or at the very beginning of the migration event in the low altitude.

Are these gaps in the data or is this due to the `0` migration values?

**Comment by peterdesmet** [comment]
Any need to fix this?

**Comment by jshamoun** [comment]
I don't think we should fix gaps in data.  But it's always nice to have a distinction between a gap in the data (no data) and a zero value (measured but no migration). If I understand correctly currently we have put zeros where there are gaps. I think that is incorrect.  Would it be possible to have an n/a or something similar? Question is how to visualize if at all, could be a small dot, or for a zero small dot and when no data, then blank screen.

**Comment by peterdesmet** [comment]
This gaps are caused by #55. Fix is described in #105. Closing.
