### ISSUE TITLE
Drop when.js

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#74]
Instead of using new version of when.js, we'll refactor code to no longer work with promises (and the requirement for a library like when.js). Modules will now work serially, instead of in parallel:

1. Load data
2. Interpolate first timeframe
3. Kick off draw function (works independently from then on)
4. Move timeframe and interpolate
5. Move timeframe and interpolate
6. ...
7. User sets timeframe and interpolate
8. ...

This should make it easier to understand and built upon the code.

**Comment by peterdesmet** [comment]
We're currently using [2.2.1](https://github.com/cujojs/when/blob/master/CHANGES.md#221). The latest version on cdnjs is [2.7.1](https://github.com/cujojs/when/blob/master/CHANGES.md#271), but the latest release on GitHub is [3.7.3](https://github.com/cujojs/when/blob/master/CHANGES.md#373).

@bartaelterman, is it worth doing an upgrade? Do we need when at all (memory management)?

**Comment by peterdesmet** [comment]
This should fix #75: verify

**Comment by bartaelterman** [comment]
Fixed in 605e94ec1acdd65b9037b6cf4d688acbec821864
