### ISSUE TITLE
JS bug

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#75]
If you open the console you'll see:

    Uncaught TypeError: undefined is not a function

The error originates on [bird.js, line 207](https://github.com/enram/bird-migration-flow-visualization/blob/383cdbf4e032e77fcfe662da1328e87d02a5af14/viz/js/birds.js#L207).

**Comment by peterdesmet** [comment]
In the current version I get:

> Uncaught TypeError: field is not a function

Still on line 207.

**Comment by bartaelterman** [comment]
This happens because the animation starts to draw before the grid is ready. We could fix this, but that would mean that the animation would have to check whether a grid is available, which could become unnecessary costly later on.
I'd say we live with it.
