### ISSUE TITLE
Update projection for basemap

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#81]
The basemap currently uses the Albers projection, which was just copied from the air project. Maybe another projection would be more suitable for Belgium/Netherlands or Europe?

**Comment by hvangasteren** [comment]
Always difficult to choose the right or best projection, but this one looks really nice and has also advances in calculations I guess. When zooming out to European scale, it's also a great projection. Others?

**Comment by jshamoun** [comment]
I found the following EU recommendation here http://ec.europa.eu/eurostat/documents/4311134/4366152/Map-projections-EUROPE.pdf/460d90e4-b7f2-49b7-8962-5c860c76757d
which recommends the following for Europe:
ETRS89 Lambert Azimuthal Equal Area coordinate reference system of 2001 [ETRS -LAEA]
might not be optimal though for only BE and NL

**Comment by peterdesmet** [comment]
We'll keep projection as it is for now.
