### ISSUE TITLE
Improve colours of basemap

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#83]
The colours of the visualization currently don't show well on presentations and posters. We should improve the colours of the basemap (and particles: see #88)

## Basemap

* [x] Background colour
* [x] Border colours
* [x] Fill colour
* [x] Radar colours
* [x] Increase size of radar dots

**Comment by jshamoun** [comment]
Just a suggestion but perhaps on the black background map, or dark grey a light, bright blue would look good for the migration vectors see eg http://www.color-hex.com/color/58c0ff

**Comment by peterdesmet** [comment]
Most work done in 112162ab5385af0f4388e5621a9288a63469a0a2

Basemap now looks like this:

![after](https://cloud.githubusercontent.com/assets/600993/8097782/ef8a9aea-0fe6-11e5-87da-1135d744de44.png)

@jshamoun, forgot to try with the colour you suggested. Do you think it's worth trying on the basemap as shown above?

**Comment by hvangasteren** [comment]
This is really cool @peterdesmet. I suggest to keep this combination of layers as the default for future maps

**Comment by jshamoun** [comment]
Actually I think the darker blue you have chosen is better on this map than the bright blue (which I suggested with the black background in mind).  You color combination will also be better in greyscale print as well.

**Comment by peterdesmet** [comment]
Finalized in #115.
