### ISSUE TITLE
Load altitude profile data from a static file instead of CartoDB

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#86]
Since we're using static case study data, we should host all data as a static file and load that one at the start of the visualization, instead of querying the data for each 20 min timeframe from CartoDB. That will 1) reduce the number of calls and 2) make the visualization run completely from GitHub, independent from CartoDB.

* [x] Aggregate all data in CartoDB
* [x] Upload aggregated data in GitHub
* [x] Document data
* [ ] Read data using D3
* [ ] Remove CartoDB code
* [ ] Test

**Comment by peterdesmet** [comment]
The visualization currently expect JSON, while the file I uploaded is currently a CSV (which makes it accessible to a wide audience). If necessary, I can upload a JSON instead. Let me know.

**Comment by bartaelterman** [comment]
While investigating this issue, I came to realise that the viz treats all date times as UTC. So the time in the text field will differ 2 hours from local time.

**Comment by bartaelterman** [comment]
Fixed in the refactor: 605e94ec1acdd65b9037b6cf4d688acbec821864
