### ISSUE TITLE
Decide how to visualize density

### ISSUE THREAD

**Issue by peterdesmet** [enram/bird-migration-flow-visualization#94]
Options:

* [ ] As **particle (line) thickness** between min and max values (blocked by #93)
* [ ] As **particle colour** using a colour gradient (blocked by #93)
* [x] As **bubbles**, i.e. circles with varying radius: very different approach by drawing far fewer particles (still with a trail), but would potentially work great in combination with wind vectors.
* [x] As **heatmap** (colour gradient) below particles: can then not be used to express environmental variable, such as wind support, etc.
* [ ] As **particle density**: instead of spawning and aging particles at random, have these values depend on the density of that particular place in the grid. The disadvantage is that with high density and speed, the map can become very saturated.

**Comment by peterdesmet** [comment]
I'd like to see how a bubbles map would look like before we build one, but I couldn't really find an existing visualization of a flow, with particles generally moving in the same direction, leaving a trail and updating their size. I did find this:

1. same direction, different sizes, ~~updating size, same speed, with trail~~: http://bl.ocks.org/WardCunningham/5861122

2. ~~same direction~~, different sizes, updating size, ~~same speed~~, with trail:

    ![zde58nuxey](https://cloud.githubusercontent.com/assets/600993/8002993/a8847a16-0b73-11e5-8a9d-5839fa1e2b0a.gif)

**Comment by peterdesmet** [comment]
Two more:

3. ~~same direction, different sizes, updating size~~, same speed, ~~with trail~~ (an interesting one to adapt): http://bl.ocks.org/mbostock/1371412

4. same direction, different sizes, updating size, same speed, ~~with trail~~: http://jsfiddle.net/blakedietz/R5cRK/1/embedded/result/. This gives a pretty good impression, except that the bubbles jiggle ([discussed here](http://stackoverflow.com/questions/20725548/animating-circles-with-d3-js))

**Comment by leijnse** [comment]
I still like the idea of visualizing bird density as particle density. Would it help to take the logarithm of the bird density to control the particle density. This would at least alleviate the problem of saturating the map when the bird density becomes very high.

**Comment by peterdesmet** [comment]
@leijnse, bird density = particle density (with upper and lower boundaries) seems like the most logical way to do it for the current visualization. I'm just wondering for future visualizations if we'll be able to combine a flow for birds with a flow for wind...

**Comment by jshamoun** [comment]
We have to be careful about over clutter and I think we should discuss this. I am not sure I follow what the suggested direction is, but I also think that density can be represented by the number of vectors in the current visualization, or an underlaying heat map, but I would not want to see dots and vectors.
Furthermore wind is indeed a major issue and really missing for good interpretation of the data. I think it should be up in the priority list.  Public access data can be accessed here:
http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis2.html
or here:
http://apps.ecmwf.int/datasets/data/interim-full-daily/

**Comment by peterdesmet** [comment]
Summary of discussion today:

* @hvangasteren in support of heatmap. We don't have to reserve heat map for something else, since there is no (near future) requirement for other environmental variables (also, those could be toggled).
* @peterdesmet in support of bubbles (see /experiments) since those could work well with wind as flow visualization. Counter argument: wind as thick layer of particles as a background for a bright colour layer of fewer bird migration particles might differentiate enough. @jshamoun: bubbles need trails to clearly see direction (e.g. in a screenshot of viz).
* Particle density considered intuitive, but might be problematic for high speed (clutter) or low speed (density still interesting for flight safety, less so for migration)
* Not much support for particle thickness and colour.

Decided to experiment with heatmap and bubbles if time allows.
